/*
 * File:                AbstractSufficientStatistics.java
 * Authors:             Kevin R. Dixon
 * Company:             Sandia National Laboratories
 * Project:             Cognitive Foundry
 * 
 * Copyright Mar 2, 2011, Sandia Corporation.
 * Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
 * license for use of this work by or on behalf of the U.S. Government.
 * Export of this program may require a license from the United States
 * Government. See CopyrightHistory.txt for complete details.
 * 
 */

package gov.sandia.cognition.statistics;

import gov.sandia.cognition.util.AbstractCloneableSerializable;

/**
 * Partial implementation of SufficientStatistics
 * @param <DataType>
 * Type of data generated by the Distribution
 * @param <DistributionType>
 * Type of Distribution this is the sufficient statistics of
 * @author Kevin R. Dixon
 * @since 3.1
 */
public abstract class AbstractSufficientStatistics<DataType, DistributionType extends Distribution<? extends DataType>>
    extends AbstractCloneableSerializable
    implements SufficientStatistics<DataType, DistributionType>
{

    /** 
     * Creates a new instance of AbstractSufficientStatistics 
     */
    public AbstractSufficientStatistics()
    {
        super();
    }

    @Override
    @SuppressWarnings("unchecked")
    public AbstractSufficientStatistics<DataType, DistributionType> clone()
    {
        return (AbstractSufficientStatistics<DataType, DistributionType>) super.clone();
    }

    @Override
    public void update(
        Iterable<? extends DataType> values)
    {
        for( DataType value : values )
        {
            this.update( value );
        }
    }

}
